/** @type {import('next').NextConfig} */
const nextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'cdn.palbincdn.com',
        pathname: '/**',
      },
    ],
  },

  /**
   * Legacy URL strategy (SEO): keep old URLs live with 200 rewrites.
   *
   * Examples:
   *  - /c442240-tazas-y-platillos-cafe-personalizado.html
   *  - /p10446447-servilleta-airlaid-pliegue-americano-o-1-8-3436-personalizada-qr.html
   */
  async rewrites() {
    return [
      // Legacy category
      {
        source: '/c:id(\\d+)-:legacySlug.html',
        destination: '/legacy-category/:id?slug=:legacySlug',
      },
      {
        source: '/c:id(\\d+).html',
        destination: '/legacy-category/:id',
      },

      // Legacy product
      {
        source: '/p:id(\\d+)-:legacySlug.html',
        destination: '/legacy-product/:id?slug=:legacySlug',
      },
      {
        source: '/p:id(\\d+).html',
        destination: '/legacy-product/:id',
      },
    ];
  },

  /**
   * 301 redirects for OTHER legacy URLs (not /c* or /p*).
   * Generated by scripts/legacy-urls.js into out/redirects.json
   */
  async redirects() {
    try {
      const fs = await import('fs');
      const path = await import('path');

      const redirectsPath = path.join(process.cwd(), 'out', 'redirects.json');
      if (!fs.existsSync(redirectsPath)) return [];

      const raw = fs.readFileSync(redirectsPath, 'utf-8');
      const parsed = JSON.parse(raw);

      if (!Array.isArray(parsed)) return [];
      return parsed;
    } catch (e) {
      console.warn('[redirects] Unable to load out/redirects.json:', e?.message || e);
      return [];
    }
  },
};

export default nextConfig;
